
import config.dbConnector;
import config.session;
import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author mendo
 */
public class changepass extends javax.swing.JFrame {
    
 session sess = session.getInstance();
    
    /**
     * Creates new form 
     */
    public changepass() {
        initComponents();
}
   

  public static String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashedBytes = md.digest(password.getBytes());
        StringBuilder hexString = new StringBuilder();
        for (byte b : hashedBytes) {
            hexString.append(String.format("%02x", b));
        }
        return hexString.toString();
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
        return null;
    }
    
}
    
    private boolean updatePassword(String newPassword) {
    String userId = session.getInstance().getU_id() + "";
    String hashedNewPassword = hashPassword(newPassword); 

    if (hashedNewPassword == null) return false;

    String sql = "UPDATE user SET u_password = ? WHERE u_id = ?";

    try (Connection connect = new dbConnector().getConnection();
         PreparedStatement pst = connect.prepareStatement(sql)) {

        pst.setString(1, hashedNewPassword); // 1st placeholder
        pst.setString(2, userId);            // 2nd placeholder

        return pst.executeUpdate() > 0; 
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return false;
}
    
  private boolean verifyCurrentPassword(String enteredPassword) {
    String userId = session.getInstance().getU_id() + "";
    String sql = "SELECT u_password FROM user WHERE u_id = ?";

    try (Connection connect = new dbConnector().getConnection();
         PreparedStatement pst = connect.prepareStatement(sql)) {

        pst.setString(1, userId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String storedHashedPassword = rs.getString("u_password");
            String enteredHashedPassword = hashPassword(enteredPassword);

            System.out.println("Entered hashed password: " + enteredHashedPassword);
            System.out.println("Stored hashed password: " + storedHashedPassword);

            return storedHashedPassword.equals(enteredHashedPassword);
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return false;
}
 // ✅ Correctly placed closing brace
    
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logintext = new javax.swing.JLabel();
        change = new javax.swing.JButton();
        backlogin = new javax.swing.JLabel();
        passwordtext = new javax.swing.JLabel();
        idfieldtext = new javax.swing.JLabel();
        cpass = new javax.swing.JPasswordField();
        rpass = new javax.swing.JPasswordField();
        passwordtext1 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        passwordtext2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(171, 167, 144));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logintext.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logintext.setText("Change Password");
        jPanel2.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        change.setBackground(new java.awt.Color(241, 185, 185));
        change.setText("change");
        change.setBorderPainted(false);
        change.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                changeFocusLost(evt);
            }
        });
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jPanel2.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 228, 19));

        backlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backloginMouseClicked(evt);
            }
        });
        jPanel2.add(backlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 304, -1, -1));

        passwordtext.setText("Current Password");
        jPanel2.add(passwordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
        jPanel2.add(idfieldtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 54, 42, -1));

        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        jPanel2.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 30));
        jPanel2.add(rpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 440, 30));

        passwordtext1.setText("re- enter Password");
        jPanel2.add(passwordtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 190, 30));

        passwordtext2.setText("New Password");
        jPanel2.add(passwordtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-50 (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void changeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_changeFocusLost

    }//GEN-LAST:event_changeFocusLost

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
    String currentPass = String.valueOf(cpass.getPassword());
    String newPass = String.valueOf(pass.getPassword());
    String reenterPass = String.valueOf(rpass.getPassword());

    if (currentPass.isEmpty() || newPass.isEmpty() || reenterPass.isEmpty()) {
    JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
    System.out.println("New password: '" + newPass + "'");
System.out.println("Re-entered password: '" + reenterPass + "'");

   if (!newPass.trim().equals(reenterPass.trim())) {
    JOptionPane.showMessageDialog(this, "New passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

    if (verifyCurrentPassword(currentPass)) {
        if (updatePassword(newPass)) {
            JOptionPane.showMessageDialog(this, "Password changed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Error updating password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Incorrect current password!", "Error", JOptionPane.ERROR_MESSAGE);
    }
       
    }//GEN-LAST:event_changeActionPerformed

    private void backloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backloginMouseClicked
        aprovmanagement acc = new aprovmanagement();
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backloginMouseClicked

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpassActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        aprovmanagement log = new aprovmanagement();
        log.setVisible(true);
        this.dispose();
        login low = new login();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlogin;
    private javax.swing.JButton change;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JLabel idfieldtext;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logintext;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passwordtext;
    private javax.swing.JLabel passwordtext1;
    private javax.swing.JLabel passwordtext2;
    private javax.swing.JPasswordField rpass;
    // End of variables declaration//GEN-END:variables
}
