/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import config.dbConnector;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author mendo
 */
public class edit extends javax.swing.JFrame {

    /**
     * Creates new form edit
     */
    public edit(String id, String fname, String lname, String eMail, String pnum) {
        initComponents();
        idfieldtext.setText(id);
        firstname.setText(fname);
        lastname2.setText(lname);
        email2.setText(eMail);
        contactnumber.setText(pnum);
        
    }
    
 private boolean emailExists(String email, String userId) {
    dbConnector con = new dbConnector();

    try {
            String query = "SELECT * FROM user WHERE u_email = ? AND u_id != ?";
            try (PreparedStatement pstmt = con.getConnection().prepareStatement(query)) {
                pstmt.setString(1, email.trim());
                pstmt.setString(2, userId);
                try (ResultSet resultSet = pstmt.executeQuery()) {
                    return resultSet.next(); // True if another user has this email
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex);
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logintext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        requiredfname = new javax.swing.JLabel();
        lastnametext = new javax.swing.JLabel();
        requiredlname = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        requiredemail = new javax.swing.JLabel();
        cnumbertext = new javax.swing.JLabel();
        requiredcnumber = new javax.swing.JLabel();
        idfieldtext = new javax.swing.JLabel();
        Signup = new javax.swing.JButton();
        backlogin = new javax.swing.JLabel();
        idfield = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname2 = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        contactnumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(239, 232, 180));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logintext.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logintext.setText("EDIT INFORMATION");
        jPanel2.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 81, 190, -1));

        requiredfname.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 139, 180, 10));

        lastnametext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastnametext.setText("Last Name");
        jPanel2.add(lastnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 81, 200, -1));

        requiredlname.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 139, 190, 10));

        emailtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailtext.setText("Email");
        jPanel2.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 153, 200, -1));

        requiredemail.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 209, 190, 10));

        cnumbertext.setText("Contact Number");
        jPanel2.add(cnumbertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 153, -1, -1));

        requiredcnumber.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 207, 190, 10));

        idfieldtext.setText("ID:");
        jPanel2.add(idfieldtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 54, -1, -1));

        Signup.setBackground(new java.awt.Color(204, 204, 204));
        Signup.setText("Edit");
        Signup.setBorderPainted(false);
        Signup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SignupFocusLost(evt);
            }
        });
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        jPanel2.add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 230, 30));

        backlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-50 (1).png"))); // NOI18N
        backlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backloginMouseClicked(evt);
            }
        });
        jPanel2.add(backlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel2.add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 10, 10));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 30));
        jPanel2.add(lastname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 30));

        email2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email2ActionPerformed(evt);
            }
        });
        jPanel2.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 30));
        jPanel2.add(contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignupFocusLost

    }//GEN-LAST:event_SignupFocusLost

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed

       if (signUpValidation()) {
            dbConnector con = new dbConnector();
            con.updateData("UPDATE user SET u_fname = '" + firstname.getText() + "', u_lname = '" + lastname2.getText() + "', "
                    + "u_email = '" + email2.getText() + "', u_number = '" + contactnumber.getText() + "' "
                    + "WHERE u_id = '" + idfieldtext.getText() + "'");
            
            JOptionPane.showMessageDialog(this, "Account's Information Updated Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            aprovmanagement ur = new aprovmanagement();
            ur.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Edit Information error. Please fill all required fields.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SignupActionPerformed
private boolean signUpValidation() {
        boolean valid = true;

        // First Name Validation
        if (firstname.getText().isEmpty()) {
            firstname.setForeground(Color.RED);
            requiredfname.setText("First Name is required");
            valid = false;
        } else {
            firstname.setForeground(Color.BLACK);
            requiredfname.setText("");
        }

        // Last Name Validation
        if (lastname2.getText().isEmpty()) {
            lastname2.setForeground(Color.RED);
            requiredlname.setText("Last Name is required");
            valid = false;
        } else {
            lastname2.setForeground(Color.BLACK);
            requiredlname.setText("");
        }

        // Email Validation
        String email1 = email2.getText();
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";

        if (email1.isEmpty()) {
            email2.setForeground(Color.RED);
            requiredemail.setText("Email is required");
            valid = false;
        } else if (!email1.matches(emailRegex)) {
            email2.setForeground(Color.RED);
            requiredemail.setText("Email is invalid");
            valid = false;
        } else if (emailExists(email1, idfieldtext.getText())) {
            email2.setForeground(Color.RED);
            requiredemail.setText("Email already exists");
            valid = false;
        } else {
            email2.setForeground(Color.BLACK);
            requiredemail.setText("");
        }

        // Contact Number Validation
        String con = contactnumber.getText();
        if (con.isEmpty()) {
            contactnumber.setForeground(Color.RED);
            requiredcnumber.setText("Contact Number is required");
            valid = false;
        } else if (!con.matches("\\d{11}")) {
            contactnumber.setForeground(Color.RED);
            requiredcnumber.setText("Contact Number must be exactly 11 digits");
            valid = false;
        } else {
            contactnumber.setForeground(Color.BLACK);
            requiredcnumber.setText("");
        }

        return valid;
    }

    private void backloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backloginMouseClicked
        aprovmanagement acc = new aprovmanagement();
    acc.setVisible(true);
    this.dispose();
       
    }//GEN-LAST:event_backloginMouseClicked

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void email2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                String id = null;
                String fname = null;
                String lname = null;
                String pnum = null;
                String eMail = null;

                new edit(id, fname, lname, pnum, eMail).setVisible(true);
            
            }
                
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Signup;
    private javax.swing.JLabel backlogin;
    private javax.swing.JLabel cnumbertext;
    private javax.swing.JTextField contactnumber;
    private javax.swing.JTextField email2;
    private javax.swing.JLabel emailtext;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel idfield;
    private javax.swing.JLabel idfieldtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname2;
    private javax.swing.JLabel lastnametext;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel requiredcnumber;
    private javax.swing.JLabel requiredemail;
    private javax.swing.JLabel requiredfname;
    private javax.swing.JLabel requiredlname;
    // End of variables declaration//GEN-END:variables
}
