
import config.dbConnector;
import java.awt.Color;
import java.awt.Font;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mendo
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public register() {
        initComponents();
        
    }
    
    
    String email, user1;

    public boolean duplicateChecker() {
    dbConnector dbc = new dbConnector();

    try {
        String query = "SELECT * FROM user WHERE u_username = '" + user.getText() + "' OR u_email = '" + email1.getText() + "'";
        ResultSet resultSet = dbc.getData(query);

        if (resultSet.next()) {
            email = resultSet.getString("u_email");
            if (email.equals(email1.getText())) {
                JOptionPane.showMessageDialog(null, "Email already used!");
                email1.setText("");
            }
            user1 = resultSet.getString("u_username");
            if (user1.equals(user.getText())) {
                JOptionPane.showMessageDialog(null, "Username already used!");
                user.setText("");
            }
            return true;
        }
    } catch (SQLException ex) {
        System.out.println("Error: " + ex.getMessage());
    }
    return false;
}
    private boolean emailExists(String email) {

        dbConnector con = new dbConnector();

        try {
            String query = "SELECT * FROM user WHERE u_email = ?";
            PreparedStatement pstmt = con.getConnection().prepareStatement(query);
            pstmt.setString(1, email.trim());
            ResultSet resultSet = pstmt.executeQuery();

            if (resultSet.next()) {

                return true;
            }

        } catch (SQLException ex) {
            System.out.println("" + ex);

        }

        return false;

    }

    Color mycolor = new Color(202, 70, 70);
    Color headcolor = new Color(234, 207, 181);
    Color bodycolor = new Color(11, 180, 158);
    Color panel = new Color(162, 158, 152);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        fn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        pn1 = new javax.swing.JLabel();
        errorLabelEmail = new javax.swing.JLabel();
        us = new javax.swing.JLabel();
        pw = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        firstname2 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        acct = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 207, 181));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(211, 180, 158));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(234, 207, 181));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/angelo-removebg-preview.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 240, 290, 190));

        jPanel21.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        lastname.setBackground(new java.awt.Color(222, 180, 138));
        lastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastname.setBorder(new javax.swing.border.MatteBorder(null));
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel21.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 160, 20));

        phonenumber.setBackground(new java.awt.Color(222, 180, 138));
        phonenumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phonenumber.setBorder(new javax.swing.border.MatteBorder(null));
        phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenumberFocusLost(evt);
            }
        });
        phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberActionPerformed(evt);
            }
        });
        jPanel21.add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 160, 20));

        pass.setBackground(new java.awt.Color(222, 180, 138));
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setBorder(new javax.swing.border.MatteBorder(null));
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel21.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 340, 20));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("First Name");
        jPanel21.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 160, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Last Name");
        jPanel21.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 170, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Phone number");
        jPanel21.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 170, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Email");
        jPanel21.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 170, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Username");
        jPanel21.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 160, 20));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Password");
        jPanel21.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 340, 20));

        jButton2.setBackground(new java.awt.Color(155, 139, 105));
        jButton2.setText("Signup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 210, 30));
        jPanel21.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 160, 10));
        jPanel21.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 160, 10));
        jPanel21.add(pn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 160, 10));
        jPanel21.add(errorLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 170, 10));
        jPanel21.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 160, 10));

        pw.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel21.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 340, 10));

        user.setBackground(new java.awt.Color(222, 180, 138));
        user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user.setBorder(new javax.swing.border.MatteBorder(null));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel21.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 160, 20));

        firstname2.setBackground(new java.awt.Color(222, 180, 138));
        firstname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname2.setBorder(new javax.swing.border.MatteBorder(null));
        firstname2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstname2FocusLost(evt);
            }
        });
        firstname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname2ActionPerformed(evt);
            }
        });
        jPanel21.add(firstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 160, 20));

        email1.setBackground(new java.awt.Color(222, 180, 138));
        email1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email1.setBorder(new javax.swing.border.MatteBorder(null));
        email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                email1FocusLost(evt);
            }
        });
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        jPanel21.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 160, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Account Type");
        jPanel21.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 110, 20));

        acct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose account type)", "admin", "applicant", " ", " " }));
        acct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctActionPerformed(evt);
            }
        });
        jPanel21.add(acct, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 160, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-50 (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION");
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 350, 20));

        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 820, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        String lname = lastname.getText();

        if (lname.isEmpty()) {

            lastname.setForeground(mycolor);
            ln.setText("This field is required");
            ln.setForeground(mycolor);

        } else {
            lastname.setForeground(Color.BLACK);
            ln.setText("");
            ln.setForeground(mycolor);
        }

        lastname.repaint();
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void phonenumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumberFocusLost
        String phoneRegex = "^[0-9]{11}$";
        String phoneInput = phonenumber.getText();

        if (phoneInput.isEmpty()) {

            phonenumber.setForeground(mycolor);
            pn1.setText("Number is required");
            pn1.setForeground(mycolor);

        } else if (!phoneInput.matches(phoneRegex)) {

            phonenumber.setForeground(mycolor);
            pn1.setText("Number is invalid");
            pn1.setForeground(mycolor);
        } else {

            phonenumber.setForeground(Color.BLACK);
            pn1.setText("");

        }

        phonenumber.repaint();
    }//GEN-LAST:event_phonenumberFocusLost

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        String passInput = pass.getText();

        if (passInput.isEmpty()) {
            pass.setForeground(mycolor);
            pw.setText("Password is required");
            pw.setForeground(mycolor);
        } else if (passInput.length() < 8) {

            pass.setForeground(mycolor);
            pw.setText("Password too short. 8 characters or more");
            pw.setForeground(mycolor);
        } else {
            pass.setForeground(Color.BLACK);
            pw.setText("");
        }
        pass.repaint();
    }//GEN-LAST:event_passFocusLost
private String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashedBytes = md.digest(password.getBytes());

        StringBuilder sb = new StringBuilder();
        for (byte b : hashedBytes) {
            sb.append(String.format("%02x", b));
        }

        return sb.toString();
    } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException(e);
    }
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dbConnector connector = new dbConnector();
    if (signUpValidation()) {
        String hashedPassword = hashPassword(pass.getText());

        connector.insertData("INSERT INTO user (u_fname, u_lname, u_email, u_number, u_roles, u_username, u_password, u_status) "
                + "VALUES ('" + firstname2.getText() + "','" + lastname.getText() + "','" + email1.getText() + "',"
                + "'" + phonenumber.getText() + "','" + acct.getSelectedItem() + "','" + user.getText() + "','" + hashedPassword + "','Pending')");

        JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Registration fail!", "fail", JOptionPane.INFORMATION_MESSAGE);
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        login log = new login();
        log.setVisible(true);
        this.dispose();
        login low = new login();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        String lname = user.getText();

        if (lname.isEmpty()) {
            user.setForeground(mycolor);
            us.setText("This field is required");
            us.setForeground(mycolor);
        } else {
            user.setForeground(Color.BLACK);
            us.setText("");
            us.setForeground(mycolor);
        }

        user.repaint();
    }//GEN-LAST:event_userFocusLost

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void firstname2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstname2FocusLost
        String fname = firstname2.getText();

        if (fname.isEmpty()) {
            firstname2.setForeground(mycolor);
            fn.setText("This field is required");
            fn.setForeground(mycolor);
        } else {
            firstname2.setForeground(Color.BLACK);
            fn.setText("");
            fn.setForeground(mycolor);
        }

        firstname2.repaint();
    }//GEN-LAST:event_firstname2FocusLost

    private void firstname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname2ActionPerformed


    private void email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email1FocusLost

        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        String emailInput = email1.getText();

        if (emailInput.isEmpty()) {

            errorLabelEmail.setText("Email is required");
            errorLabelEmail.setForeground(Color.getColor(emailInput, mycolor));

        } else if (!emailInput.matches(emailRegex)) {

            email1.setForeground(Color.getColor(emailInput, mycolor));
            errorLabelEmail.setText("Email is invalid");
            errorLabelEmail.setForeground(Color.getColor(emailInput, mycolor));
        } else if (emailExists(emailInput)) {

            email1.setForeground(Color.getColor(emailInput, mycolor));
            errorLabelEmail.setText("Email already exists");
            errorLabelEmail.setForeground(Color.getColor(emailInput, mycolor));

        } else {

            email1.setForeground(Color.GREEN);
            errorLabelEmail.setText("Email valid");
            errorLabelEmail.setForeground(Color.GREEN);
        }

        email1.repaint();


    }//GEN-LAST:event_email1FocusLost

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void acctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctActionPerformed
    private boolean signUpValidation() {
        boolean valid = true;

        String lname = lastname.getText();

        if (lname.isEmpty()) {

            lastname.setForeground(mycolor);
            ln.setText("This field is required");
            ln.setForeground(mycolor);

        } else {
            lastname.setForeground(Color.BLACK);
            ln.setText("");
            ln.setForeground(mycolor);
        }

        lastname.repaint();

        String fname = firstname2.getText();

        if (fname.isEmpty()) {
            firstname2.setForeground(mycolor);
            fn.setText("This field is required");
            fn.setForeground(mycolor);
        } else {
            firstname2.setForeground(Color.BLACK);
            fn.setText("");
            fn.setForeground(mycolor);
        }

        firstname2.repaint();

        String passInput = pass.getText();

        if (passInput.isEmpty()) {
            pass.setForeground(mycolor);
            pw.setText("Password is required");
            pw.setForeground(mycolor);
        }else if (duplicateChecker()){
            System.out.println("duplicate exist");
        }
        else if (passInput.length() < 8) {

            pass.setForeground(mycolor);
            pw.setText("Password too short. 8 characters or more");
            pw.setForeground(mycolor);
        } else {
            pass.setForeground(Color.BLACK);
            pw.setText("");
        }
        pass.repaint();

        String lname1 = user.getText();

        if (lname1.isEmpty()) {
            user.setForeground(mycolor);
            us.setText("This field is required");
            us.setForeground(mycolor);
        } else {
            user.setForeground(Color.BLACK);
            us.setText("");
            us.setForeground(mycolor);
        }

        user.repaint();
        String phoneRegex = "^[0-9]{11}$";
        String phoneInput = phonenumber.getText();

        if (phoneInput.isEmpty()) {

            phonenumber.setForeground(mycolor);
            pn1.setText("Number is required");
            pn1.setForeground(mycolor);

        } else if (!phoneInput.matches(phoneRegex)) {

            phonenumber.setForeground(mycolor);
            pn1.setText("Number is invalid");
            pn1.setForeground(mycolor);
        } else {

            phonenumber.setForeground(Color.BLACK);
            pn1.setText("");

        }

        phonenumber.repaint();
        return (valid);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acct;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel errorLabelEmail;
    private javax.swing.JTextField firstname2;
    private javax.swing.JLabel fn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel ln;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JLabel pn1;
    private javax.swing.JLabel pw;
    private javax.swing.JLabel us;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
